### ISSUE TITLE
JS-T: META: Create configuration file for MainNet & DPTestnet

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#112]
* As a tutorial maintainer, I want an easy way to define which networks the tutorials in this repo connect to.
* As a tutorial user, I want to be able to swap between MainNet & DPTestnet by changing a single line in the tutorial

**AC**
- [x] explanation for standard location for 1->n net configurations in a comment titled `# Result/s`
- [x] creation of configurations for MainNet & DPTestnet (currently steem.vc testnet)
- [x] At least one existing tutorial updated to use the new configuration system (include which tutorial in `# Result/s`)

**Comment by relativityboy** [comment]
# Result

* Chose to locate the network configurations in the same location as the accounts for ease of reference by users.
* Each chain has a context exported from the file that contains all the configuration for that chain. This limits hunting for valid accounts and cuts down any debug time related to accounts/urls/chain ids.

**Comment by relativityboy** [comment]
#123 satisfies this issue.
