### ISSUE TITLE
JS-T: META: Centralize location of testnet tutorial accounts & keys

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#113]
* As a tutorial maintainer, I want an easy place to link to for "more" testnet "play" accounts in both the readme, and in the active tutorial code.
* As a tutorial user, I want to have options if the default accounts for a tutorial have been hijacked.

**AC**
- [x] a standardized location in this repo for testnet accounts with account names & priv keys
- [x] a file that is importable from our tutorials, or a plan for making an importable file.
- [x] explanation of what was decided & why in `# Result/s` comment

**Comment by relativityboy** [comment]
Taking the PR listed as the "results" comment. :)
