### ISSUE TITLE
JS-T: META: Centralization of testnet tutorial accounts & keys

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#116]
This tutorial builds on #113. While the data-flow was good, the browser fetch process, data-structure, and file locations looked like they'd add code complexity to individual tutorials.

* As a tutorial maintainer, I want an easy place to link to for "more" testnet "play" accounts in both the readme, and in the active tutorial code.
* As a tutorial user, I want to have options if the default accounts for a tutorial have been hijacked.

**AC**
- [x] a standardized location in this repo for testnet accounts with account names & priv keys
- [x] a file that is importable from our tutorials, or a plan for making an importable file.
- [ ] explanation of what was decided & why in `# Result/s` comment

**Comment by relativityboy** [comment]
# Results

Decided to place a configuration file within the tutorials directory, and have it be a standard `.js` file for easy maintenance (fewer `"`) and flexibility (we can update the structure of the file so that only the account, or item needing to be imported will be.

We chose to rely on a compile-time import to make the webpack configuration and the tutorial boiler-plate both little simpler and easier to maintain.
