### ISSUE TITLE
JS-T: META: Standardize the structure of all tutorials

### ISSUE THREAD

**Issue by relativityboy** [steemit/devportal-tutorials-js#69]
Standardize the tutorials based on the outcome of steemit/devportal#159

**AC**
- [x] 01_blog_feed - feruz
- [x] 02_steemconnect - feruz
- [x] 03_client_signing - feruz
- [x] 04_get_posts - relativityboy
- [x] 05_get_post_details - feruz
- [x] 06_get_voters_list_on_post - feruz
- [x] 07_get_post_comments - feruz
- [x] 08_get_account_replies - feruz
- [x] 09_get_account_comments - roboza
- [x] 10_submit_post - roboza
- [x] 11_submit_comment_reply - relativityboy
- [x] 12_edit_content_patching - feruz	

- [x] all tutorials have the same base structure.

**Comment by inertia186** [comment]
One thing we have to figure out is what to do with `right-code` from the perspective of the rake task (https://github.com/steemit/devportal/issues/163).  Options:

1. Keep `right-code` and try to parse the tutorial `README.md` file, splitting the paragraphs of the tutorial to the left and code to the right.
2. Leave `right-code` blank and just manually move code over to `right-code` if it makes sense.
3. Create a `right-code.js` file just for code examples that belong in `right-code`.
4. Eliminate `right-code` and just import the `README.md` as is.

I've been working on option 1, but I don't think we'll like the results.  Some tutorials have only one code example per heading, and that works great.  But some tutorials have multiple code examples per heading and they just get moved over to  `right-code`, making the flow of the paragraph awkward.

Personally, I'd go with option 4.

**Comment by relativityboy** [comment]
We have determined "right code" will be signified by code blocks created with `~~~`

Specification is in the `-js` repository

**Comment by feruzm** [comment]
I will start first 3 (get blog, steemconnect, client signing) tutorials and push them to `69-readme-structure` branch later today

**Comment by relativityboy** [comment]
I added each story as an AC at the top. We can check them off as they get done.

**Comment by relativityboy** [comment]
I will take **04_get_posts**.
